apiVersion: v1
kind: Pod
metadata:
  name: wineapp-food-service
  labels:
    wineapp: "1.0"
spec:
  containers:
  - env:
    - name: DATABASE_FQDN
      value: wineapp-postgresql
    - name: DATABASE_NAME
      value: winedb
    - name: DATABASE_USER
      value: userMhe
    - name: DATABASE_PASSWORD
      value: aDb5oeeE
    image: 172.30.121.33:5000/with-secrets/wineapp-food-service
    imagePullPolicy: Always
    name: wineapp-food-service
    ports:
    - containerPort: 8080
      protocol: TCP
  restartPolicy: Never