apiVersion: v1
kind: Service
metadata:
  labels:
    wineapp: "1.0"
  name: wineapp-food-service
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: wineapp-food-service
  sessionAffinity: None
  type: ClusterIP
