apiVersion: v1
kind: Service
metadata:
  labels:
    wineapp: "1.0"
  name: wineapp-wine-service
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: wineapp-wine-service
  sessionAffinity: None
  type: ClusterIP
