apiVersion: v1
kind: Pod
metadata:
  name: wineapp-wine-service
  labels:
    wineapp: "1.0"
    name: wineapp-wine-service
spec:
  containers:
  - env:
    - name: DATABASE_FQDN
      value: wineapp-postgresql
    - name: DATABASE_NAME
      value: winedb
    - name: DATABASE_USER
      value: admin
    - name: DATABASE_PASSWORD
      value: supersekret
    image: 172.30.118.98:5000/without-secrets/wineapp-wine-service
    imagePullPolicy: Always
    name: wineapp-wine-service
    ports:
    - containerPort: 8080
      protocol: TCP
  restartPolicy: Never