apiVersion: v1
kind: Pod
metadata:
  name: wineapp-food-service
  labels:
    wineapp: "1.0"
    name: wineapp-food-service
spec:
  containers:
  - env:
    - name: DATABASE_FQDN
      value: wineapp-postgresql
    - name: DATABASE_NAME
      value: winedb
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: db-user-pass
          key: username
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-user-pass
          key: password
    image: 172.30.121.33:5000/without-secrets/wineapp-food-service:latest
    imagePullPolicy: Always
    name: wineapp-food-service
    ports:
    - containerPort: 8080
      protocol: TCP
  restartPolicy: Never