apiVersion: v1
kind: Pod
metadata:
  generateName: wineapp-ui-1-
  labels:
    name: wineapp-ui
  name: wineapp-ui
spec:
  containers:
  - env:
    - name: FOOD_SERVICE
      value: wineapp-food-service
    - name: WINE_SERVICE
      value: wineapp-wine-service
    image: 172.30.235.66:5000/with-secrets/wineapp-ui:latest
    imagePullPolicy: Always
    name: wineapp-ui
    ports:
    - containerPort: 8080
      protocol: TCP
